### ISSUE TITLE
transition for particular frame

### ISSUE THREAD

**Issue by dcherian** [jberger/MakeBeamerInfo#1]
I generally use no transitions. But sometimes, one particular slide benefits from a transition. Currently, I have to use makebeamerinfo to create the `.info` file, then find the appropriate slide number and then manually edit the `.info` file to add the transition in the right place.

It would be nice to support the `%O` syntax of `impressive-gettransitions` just for this purpose: setting the transition on particular slides.

Does this sound like a good idea to you?

**Comment by jberger** [comment]
How would you propose to designate that information?

**Comment by dcherian** [comment]
How about 

```
\begin{frame}
%makebeamerinfo transition: PagePeel
\end{frame}
```

**Comment by jberger** [comment]
MakeBeamerInfo doesn't parse the actual tex file at all, it uses a
generated metadata file to extract its information. Adding it that way
would be quite a large task.

**Comment by dcherian** [comment]
I guess there's no way to do this then. Unfortunate.

**Comment by jberger** [comment]
I didn't mean to be so discouraging, and I'm sorry if I'm a little terse
since MakeBeamerInfo isn't on the top of mind for me lately. I'd be
interested to consider some kind of configuration file if it was clean and
useful. My biggest worry for that is if you add a slide and then forget to
change the config. The major point of automating things in the way that I
did was that it was a slightly opinionated way of getting a useable default
info file.

**Comment by dcherian** [comment]
> My biggest worry for that is if you add a slide and then forget to
> change the config.

Yeah, that's the problem I'm running into. The only logical place to put a specification is then in the .tex file like what `impressive-gettransitions` does. But unfortunately, it does not count the slides right.

**Comment by jberger** [comment]
Thus the reason I used an auxiliary file which is generated as part of the
build process. I knows much more accurately what the final render will
result in.
